# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 880382620cf02a33c722d4dba60553251351e4df3a787d1deb960aa6e844fa138d60b78a65578edce161cd7b35a8fb58fc5ed560003117a1aa64eb0ed3268bd8

test:
  secret_key_base: 201cac286c19e617b9992fa926bc0cfff89a5cce2ca1c2fbdd25a2548b9eb154d335d69bf9a7ede60f5df2182115db54227431db14d164a735a8d90ac3eadbec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
